[meta]
title = "Django Live Transcription Starter"
description = "Get started using Deepgram's Live Transcription with this Django demo app"
author = "Deepgram DX Team <devrel@deepgram.com> (https://developers.deepgram.com)"
useCase = "Live STT"
language = "Python"
framework = "Django"
sdk = "4.8.1"

[build]
command = "pip install -r requirements.txt"

[post-build]
message = "Run `python app.py` to start the Django live transcription server."
