[meta]
title = "Django Live Transcription"
description = "Get started using Deepgram's Live Transcription with this Django demo app"
author = "Deepgram DX Team <devrel@deepgram.com> (https://developers.deepgram.com)"
useCase = "Live STT"
language = "Python"
framework = "Django"
sdk = "N/A"
repository = "https://github.com/deepgram-starters/django-live-transcription"

[build]
command = "pip install -r requirements.txt"

[post-build]
message = "Run `python app.py` to start the Django live transcription server."
